import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "../components/layout/Navbar";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata = {
  title: "EcoloShop - Boutique de vente d'objets écologiques",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="fr"
      className={`${outfit.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col px-6 md:px-[10%]">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
